env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
project_name: jdbc-parser
release:
  github:
    owner: UnAfraid
    name: jdbc-parser
  name_template: '{{.Tag}}'
builds:
  - id: release
    ldflags: -s -w -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
archives:
  - name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - release
    format_overrides:
      - goos: windows
        format: zip
